#!/usr/bin/env python3
"""
build_report.py -- Validate and assemble the STYLE-FREE CONTENT of a de novo binder
design report from a small JSON config plus the pipeline's standard output files, and
run the consistency gate. It does NOT style or render the PDF: it writes an ordered list
of style-free content blocks (headings, paragraphs, tables, callouts, figures, sequences)
to --out, and the pdf-report-generation skill renders that content into the final, styled
PDF (with the platform's running-header and footer rules). Report styling is owned by the
platform (the pdf-report-generation skill), not by this script.

Stage 4b of the workflow (RFdiffusion -> ProteinMPNN -> Boltz-2 -> figures -> report
content + gate -> pdf-report-generation render).

This is target-AGNOSTIC: all target-specific text (protein name, PDB, epitope, rationale)
comes from --config, and all quantitative content comes from the ranking CSV / metrics
JSON produced by analyze_interface.py. Nothing about the target is hard-coded.

Structure facts (resolution, experimental method, deposition date) are FETCHED from the PDB
by fetch_structure_metadata.py and read from its structure_metadata.json sidecar -- they are
never hand-typed in the config. The construct's residue span is DERIVED from prepare_target.py's
construct_scope.json sidecar, not restated in the config. A consistency gate fails the build if
the config tries to hand-supply either (see CONSISTENCY GATE).

Campaign counts (n_backbones, n_sequences, n_passed, n_validated) are DERIVED from the
pipeline artifacts (--all-sequences-csv, --selected-csv, the ranking CSV) rather than
read from the config. If the config still carries those keys, they are cross-checked
against the derived values and a mismatch fails the build (see verify_report_inputs).

CONFIG JSON (see references/report_config_template.json) -- keys:
  target_name        e.g. "PCSK9 catalytic domain"
  target_pdb         e.g. "2P4E"                  (id/input; its FACTS are fetched, not typed)
  target_uniprot     e.g. "Q8NBP7"                (optional)
  domain_label       e.g. "IgV domain"            (optional; biological NAME only, no residue range)
  structure_metadata path to structure_metadata.json from fetch_structure_metadata.py
                     (fetched resolution/method/deposition; may also be given via --structure-metadata)
  construct_scope    path to construct_scope.json from prepare_target.py --scope-out
                     (SOURCE of the derived construct span; may also be given via --construct-scope)
  rationale          1-3 sentence paragraph on why this target/epitope
  epitope_note       1-2 sentences describing the targeted region (optional)
  binder_len_range   e.g. "60-90"
  hotspots           list of declared hotspot residue numbers (cross-checked vs metrics)
  functional_site    list of functional-site residue numbers (optional)
  filters            dict of the filter thresholds used (free-form; printed verbatim)
  figures            dict mapping caption-slots to figure PNG paths, keys:
                       mpnn_scores, boltz_metrics, interfaces  (any subset)
  correlation_note   OPTIONAL preformatted sentence on MPNN-vs-ipTM agreement.
                     If omitted, it is computed from the ranking CSV with the
                     sign-consistent convention (see below).
  author_line        e.g. "Generated by Biomni"  (optional)

CORRELATION (computed if not supplied):
  Reports raw Spearman(mpnn_score, ipTM) so the sign matches a scatter of those axes.
  Because lower MPNN = better and higher ipTM = better, a NEGATIVE raw rho means the
  metrics AGREE. Also states whether top-half / bottom-half candidate SETS agree.

CONSISTENCY GATE (verify_report_inputs):
  Before writing the PDF, the builder checks that: (a) the config carries NO hand-typed
  structure facts or construct span (those are fetched/derived); (b) if a PDB is named, a
  fetched structure_metadata.json sidecar exists, carries provenance, and is for that same
  PDB; (c) the construct span in construct_scope.json matches the target_range echoed on the
  metrics records; (d) the ranking CSV and metrics JSON agree on candidate sets, ipTM/iface_pae
  values, hotspot declarations, and figure files. On failure it exits 2 with a numbered remedy
  list. Use --no-strict to downgrade to printed warnings plus a 'Provenance warnings' callout
  in the PDF.

OUTPUT
  --out  path to the validated, style-free report-content JSON. Render it into the final
         PDF with the pdf-report-generation skill (it owns the styling). JSON is a
         sequential write, so it can go straight to /mnt/results/ if desired.

EXIT CODES
  0 success; 2 usage/input error or consistency-gate failure.
"""
import argparse
import json
import os
import sys
from datetime import date


def die(msg, code=2):
    sys.stderr.write(f"[build_report] ERROR: {msg}\n")
    sys.exit(code)


# Structure facts (resolution, method, deposition date, chain composition) are FETCHED
# from the PDB via fetch_structure_metadata.py, and the construct span is DERIVED from
# construct_scope.json. Neither may be hand-typed into the config -- a hand-typed
# external-database fact is exactly the failure mode this gate exists to prevent
# (e.g. a config that says "2.10 A" when RCSB reports 0.99 A). If any of these keys
# appears in the config, the build fails with a remove-this-key remedy.
FORBIDDEN_STRUCTURE_KEYS = (
    "target_resolution", "resolution", "target_method", "experimental_method",
    "exptl_method", "deposition_date", "deposit_date", "release_date",
    "structure_title", "polymer_composition", "domain_range",
)


def load_json(path):
    """Load a JSON sidecar, or return None if the path is empty/missing."""
    if not path:
        return None
    if not os.path.isfile(path):
        return None
    with open(path) as fh:
        return json.load(fh)


def _norm_pdb(x):
    return str(x).strip().upper() if x else ""


def structure_fact(struct_meta, key):
    """Return a fetched structure fact, or None if unavailable.

    A value is returned ONLY when it came from a successful fetch (available=True)
    and is non-null. Otherwise None -> the report renders 'unavailable'. There is no
    fallback to a config/typed value: that path does not exist anymore.
    """
    if struct_meta and struct_meta.get("available") and struct_meta.get(key) is not None:
        return struct_meta.get(key)
    return None


def resolution_str(struct_meta):
    r = structure_fact(struct_meta, "resolution_A")
    return f"{r:.2f} \u00c5" if isinstance(r, (int, float)) else "unavailable"


def construct_span_bits(cfg, scope):
    """Derive the construct span from construct_scope.json (the single source).

    Returns (realised_range, explanation) where explanation is a nominal-vs-realised
    sentence when the requested core differs from what was actually built, else None.
    The construct span is NEVER read from the config -- it is what prepare_target.py
    actually produced.
    """
    if not scope:
        return (None, None)
    realised = str(scope.get("target_range") or "").strip() or None
    core = str(scope.get("core_range") or "").strip() or None
    margin = scope.get("margin")
    mode = scope.get("margin_mode")
    label = (cfg.get("domain_label") or "").strip()
    if realised and core and core != realised:
        margin_clause = ""
        if margin:
            try:
                margin_clause = f" after a {float(margin):g} \u00c5 {mode or 'spatial'} margin"
            except (TypeError, ValueError):
                margin_clause = ""
        lead = f"nominal {label} " if label else "requested "
        explanation = (f"{lead}core {core}; the built construct spans {realised}{margin_clause} "
                       f"(residues pulled in by the crop are part of the designed interface).")
        return (realised, explanation)
    # no divergence: realised == core (or core unknown)
    return (realised, None)


def compute_correlation_note(rank_df):
    """Sign-consistent MPNN-vs-ipTM agreement sentence from the ranking table."""
    if "mpnn_score" not in rank_df.columns or rank_df["mpnn_score"].isna().any():
        return None
    try:
        from scipy.stats import spearmanr
    except Exception:
        return None
    n = len(rank_df)
    if n < 3:
        return None
    rho, p = spearmanr(rank_df["mpnn_score"], rank_df["iptm"])
    k = max(1, n // 2)
    by_mpnn = rank_df.sort_values("mpnn_score")
    top_mpnn = set(by_mpnn.head(k)["candidate"])
    by_iptm = rank_df.sort_values("iptm", ascending=False)
    top_iptm = set(by_iptm.head(k)["candidate"])
    agree = top_mpnn == top_iptm
    direction = ("agree (a negative raw correlation is expected here because lower "
                 "ProteinMPNN score and higher ipTM both indicate better designs)"
                 if rho < 0 else "point in inconsistent directions")
    setmsg = (f"the same {k} candidates rank in the top half by both metrics"
              if agree else "the top-half candidate sets differ between the two metrics")
    return (f"Across the {n} validated candidates, the raw Spearman correlation between "
            f"ProteinMPNN score and ipTM is {rho:+.2f} (p = {p:.2f}); the two metrics "
            f"{direction}. At the set level, {setmsg}, though the fine ordering within "
            f"the top set can differ, which is why structure-based validation is used to "
            f"pick the final winner.")


def verify_report_inputs(cfg, rank, metrics, derived, struct_meta=None, scope=None, strict=True):
    """Check that report claims match the produced artifacts. Returns list of warnings.

    If strict is True and any check fails, exit 2 with a numbered remedy list.
    If strict is False, return the warning list for display in the PDF.

    struct_meta: the loaded structure_metadata.json sidecar (fetched from the PDB), or None.
    scope:       the loaded construct_scope.json sidecar (from prepare_target.py), or None.
    """
    warnings = []

    # (0) NO hand-typed structure facts / construct span in the config.
    # Structure facts are fetched (fetch_structure_metadata.py); the construct span is
    # derived (construct_scope.json). A hand-typed value here is the exact hallucination
    # class this gate prevents.
    for k in FORBIDDEN_STRUCTURE_KEYS:
        if k in cfg and cfg[k] not in (None, "", [], {}):
            warnings.append(
                f"Config carries hand-typed key {k!r}. Structure facts (resolution, method, "
                f"deposition date) are fetched from the PDB via fetch_structure_metadata.py, and "
                f"the construct span is derived from construct_scope.json; neither may be set by "
                f"hand. Remedy: remove {k!r} from the config.")

    # (1) candidate sets in rank and metrics are identical
    rank_cands = set(rank["candidate"].tolist())
    metrics_cands = set(metrics.keys())
    if rank_cands != metrics_cands:
        only_rank = rank_cands - metrics_cands
        only_metrics = metrics_cands - rank_cands
        parts = []
        if only_rank:
            parts.append(f"in ranking CSV only: {sorted(only_rank)}")
        if only_metrics:
            parts.append(f"in metrics JSON only: {sorted(only_metrics)}")
        warnings.append(f"Candidate sets differ between ranking CSV and metrics JSON ({'; '.join(parts)}). "
                        f"Remedy: re-run analyze_interface.py to regenerate both from the same candidates.")

    # (2) iptm and iface_pae agree between CSV and JSON to 4 dp for every candidate
    for cid in sorted(rank_cands & metrics_cands):
        row = rank[rank["candidate"] == cid].iloc[0]
        md = metrics[cid]
        for col in ("iptm", "iface_pae"):
            csv_val = row.get(col)
            json_val = md.get(col)
            if csv_val is None and json_val is None:
                continue
            if csv_val is None or json_val is None:
                warnings.append(f"{cid}: {col} present in one source but not the other "
                                f"(CSV={csv_val}, JSON={json_val}). "
                                f"Remedy: re-run analyze_interface.py to regenerate both.")
                continue
            try:
                if round(float(csv_val), 4) != round(float(json_val), 4):
                    warnings.append(f"{cid}: {col} disagrees between CSV ({csv_val}) and JSON ({json_val}). "
                                    f"Remedy: re-run analyze_interface.py; do not hand-edit the ranking table.")
            except (TypeError, ValueError):
                warnings.append(f"{cid}: {col} has non-numeric value (CSV={csv_val}, JSON={json_val}). "
                                f"Remedy: re-run analyze_interface.py.")

    # (3) config count keys must equal derived values if present
    for key, derived_val in derived.items():
        if key in cfg and cfg[key] is not None:
            try:
                cfg_val = int(cfg[key])
                if cfg_val != derived_val:
                    warnings.append(f"Config {key}={cfg_val} disagrees with derived value {derived_val}. "
                                    f"Remedy: remove the key from the config (derived values are used) or "
                                    f"fix the config to match the artifacts.")
            except (TypeError, ValueError):
                warnings.append(f"Config {key}={cfg[key]!r} is not an integer; derived value is {derived_val}. "
                                f"Remedy: remove the key from the config or set it to {derived_val}.")

    # (4a) structure metadata must be FETCHED (with provenance) for the named PDB.
    # This is the provenance gate: if the report names a PDB it must carry fetched
    # metadata for that same PDB, and that metadata must have a provenance block.
    # If the fetch failed (available=false) the sidecar still exists with an error
    # recorded -- that is honest ("unavailable") and passes; a MISSING sidecar or a
    # PDB mismatch does not.
    pdb = _norm_pdb(cfg.get("target_pdb"))
    if pdb:
        if not struct_meta:
            warnings.append(
                f"Report names PDB {pdb} but no fetched structure metadata was provided. "
                f"Remedy: run scripts/fetch_structure_metadata.py --pdb {pdb} --out structure_metadata.json "
                f"and pass --structure-metadata (or set 'structure_metadata' in the config). "
                f"Structure facts must be read from the PDB, not typed by hand.")
        else:
            prov = struct_meta.get("provenance") or {}
            if not prov.get("source_url") or not prov.get("fetched_at"):
                warnings.append(
                    "Structure metadata sidecar has no provenance (source_url + fetched_at). "
                    "Remedy: regenerate it with fetch_structure_metadata.py; do not hand-write it.")
            sm_pdb = _norm_pdb(prov.get("pdb_id") or struct_meta.get("pdb_id"))
            if sm_pdb and sm_pdb != pdb:
                warnings.append(
                    f"Structure metadata is for PDB {sm_pdb} but the report names PDB {pdb}. "
                    f"Remedy: fetch metadata for {pdb} (fetch_structure_metadata.py --pdb {pdb}).")

    # (4b) the construct span is DERIVED from construct_scope.json, and that scope must
    # agree with the target_range echoed on every metrics record (one source of truth
    # for what was actually built). Replaces the old hand-typed domain_range check.
    target_ranges = {str(md.get("target_range", "")).strip()
                     for md in metrics.values() if md.get("target_range")}
    if len(target_ranges) > 1:
        warnings.append(f"Metrics records have inconsistent target_range values: {sorted(target_ranges)}. "
                        f"Remedy: re-run analyze_interface.py with a consistent --domain-start.")
    metrics_tr = target_ranges.pop() if len(target_ranges) == 1 else None
    if not scope:
        warnings.append(
            "No construct_scope.json provided; the construct span is derived from it, not restated "
            "in the config. Remedy: pass --construct-scope (or set 'construct_scope' in the config) "
            "pointing at prepare_target.py's --scope-out sidecar.")
    else:
        scope_tr = str(scope.get("target_range") or "").strip()
        if not scope_tr:
            warnings.append(
                "construct_scope.json has no target_range. "
                "Remedy: regenerate it with prepare_target.py --scope-out.")
        elif metrics_tr and scope_tr != metrics_tr:
            warnings.append(
                f"construct_scope target_range={scope_tr!r} disagrees with metrics target_range={metrics_tr!r}. "
                f"The realised construct span must have a single source. Remedy: regenerate "
                f"construct_scope.json and the metrics from the same crop (prepare_target.py --scope-out, "
                f"then analyze_interface.py --domain-start = construct_scope.domain_start).")

    # (5) config hotspots must equal hotspots_declared on metrics records
    if cfg.get("hotspots") is not None:
        cfg_hs = sorted(int(x) for x in cfg["hotspots"])
        declared_sets = []
        for md in metrics.values():
            hd = md.get("hotspots_declared")
            if hd is not None:
                declared_sets.append(tuple(sorted(hd)))
        if declared_sets:
            unique_declared = set(declared_sets)
            if len(unique_declared) == 1:
                metrics_hs = sorted(unique_declared.pop())
                if cfg_hs != metrics_hs:
                    warnings.append(f"Config hotspots={cfg_hs} disagrees with metrics hotspots_declared={metrics_hs}. "
                                    f"Remedy: set hotspots in the config to {metrics_hs} or remove it.")
            elif len(unique_declared) > 1:
                warnings.append(f"Metrics records have inconsistent hotspots_declared values. "
                                f"Remedy: re-run analyze_interface.py with a consistent --hotspots.")
            if not cfg_hs and any(d for d in declared_sets if d):
                warnings.append(f"Config hotspots is empty but metrics records declare hotspots. "
                                f"Remedy: set hotspots in the config to match the declared set.")

    # (6) every figure path exists and has a sibling .svg of non-zero size
    for slot, path in cfg.get("figures", {}).items():
        if not path:
            continue
        if not os.path.isfile(path):
            warnings.append(f"Figure '{slot}' path does not exist: {path}. "
                            f"Remedy: run make_figures.py or fix the path in the config.")
            continue
        svg_path = os.path.splitext(path)[0] + ".svg"
        if not os.path.isfile(svg_path) or os.path.getsize(svg_path) == 0:
            warnings.append(f"Figure '{slot}' has no non-zero sibling SVG: {svg_path}. "
                            f"Remedy: re-run make_figures.py (it writes both PNG and SVG).")

    # (7) if any candidate has epitope_status == NOT_ASSESSED, require explicit disclosure
    not_assessed = [cid for cid, md in metrics.items() if md.get("epitope_status") == "NOT_ASSESSED"]
    if not_assessed:
        # This is a warning, not a hard failure -- the report must disclose it (handled in story).
        # But we flag it so the caller knows to emit the ORANGE callout.
        pass

    if strict and warnings:
        sys.stderr.write("[build_report] CONSISTENCY GATE FAILED:\n")
        for i, w in enumerate(warnings, 1):
            sys.stderr.write(f"  {i}. {w}\n")
        sys.exit(2)
    return warnings


def main():
    ap = argparse.ArgumentParser(
        description="Validate and assemble the style-free CONTENT of a binder-design report, then "
                    "run the consistency gate. The styled PDF is rendered from this content by the "
                    "pdf-report-generation skill.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    ap.add_argument("--config", required=True, help="Campaign config JSON (target metadata + params).")
    ap.add_argument("--ranking-csv", required=True, help="analyze_interface.py ranked CSV.")
    ap.add_argument("--metrics-json", required=True, help="analyze_interface.py per-candidate JSON.")
    ap.add_argument("--all-sequences-csv", default=None,
                    help="filter_sequences.py all-sequences CSV (for deriving campaign counts).")
    ap.add_argument("--selected-csv", default=None,
                    help="filter_sequences.py selected CSV (for deriving n_selected).")
    ap.add_argument("--structure-metadata", default=None,
                    help="structure_metadata.json sidecar from fetch_structure_metadata.py "
                         "(fetched PDB facts). May also be set as 'structure_metadata' in the config. "
                         "Required when target_pdb is set.")
    ap.add_argument("--construct-scope", default=None,
                    help="construct_scope.json sidecar from prepare_target.py --scope-out. May also be "
                         "set as 'construct_scope' in the config. Source of the derived construct span.")
    ap.add_argument("--out", required=True,
                    help="Output path for the validated, style-free report-content JSON. Render it into "
                         "a PDF with the pdf-report-generation skill (which owns the styling).")
    ap.add_argument("--top-n", type=int, default=3, help="Number of top candidates to feature.")
    ap.add_argument("--no-strict", action="store_true",
                    help="Downgrade consistency-gate failures to warnings + a warning block in the content.")
    args = ap.parse_args()

    for f in (args.config, args.ranking_csv, args.metrics_json):
        if not os.path.isfile(f):
            die(f"missing input: {f}")

    try:
        import pandas as pd
    except ImportError as e:
        die(f"missing dependency: {e} (need pandas).")

    cfg = json.load(open(args.config))
    rank = pd.read_csv(args.ranking_csv)
    metrics = json.load(open(args.metrics_json))
    datestr = date.today().strftime("%B %d, %Y")

    # Fetched structure facts and the derived construct span come from sidecars, not the
    # config. CLI flag wins; otherwise fall back to a path named in the config.
    struct_meta = load_json(args.structure_metadata or cfg.get("structure_metadata"))
    scope = load_json(args.construct_scope or cfg.get("construct_scope"))

    # ---------- derive campaign counts from artifacts ----------
    derived = {}
    all_seq = None
    selected = None
    if args.all_sequences_csv and os.path.isfile(args.all_sequences_csv):
        all_seq = pd.read_csv(args.all_sequences_csv)
        derived["n_backbones"] = int(all_seq["design"].nunique())
        derived["n_sequences"] = len(all_seq)
        if "pass" in all_seq.columns:
            derived["n_passed"] = int(all_seq["pass"].sum())
    if args.selected_csv and os.path.isfile(args.selected_csv):
        selected = pd.read_csv(args.selected_csv)
        derived["n_selected"] = len(selected)
    derived["n_validated"] = len(rank)

    # Helper to get a derived count, falling back to config only if artifacts unavailable.
    def dcount(key, fallback="N"):
        if key in derived:
            return derived[key]
        return cfg.get(key, fallback)

    figs = cfg.get("figures", {})

    # ---------- assemble STYLE-FREE content blocks ----------
    # Each block is a plain dict {"type": ..., ...}. No colour, font, page geometry, or
    # brand palette is decided here -- that is owned by the pdf-report-generation skill,
    # which renders these blocks into the styled PDF. Callout accents are SEMANTIC roles
    # ("danger"/"warning"/"neutral"), never hex colours, so the scientific meaning (which
    # callouts are warnings) survives without the report builder styling anything.
    blocks = []

    def para(text):
        blocks.append({"type": "paragraph", "text": text})

    def section(title):
        blocks.append({"type": "section", "title": title})

    def subsection(title):
        blocks.append({"type": "subsection", "title": title})

    def callout(title, text, role="neutral"):
        blocks.append({"type": "callout", "title": title, "text": text, "role": role})

    def figure(path, caption):
        blocks.append({"type": "figure", "path": path, "caption": caption})

    def sequence(label, seq):
        if seq:
            blocks.append({"type": "sequence", "label": label, "seq": seq})

    # ---------- Title ----------
    blocks.append({"type": "title",
                   "text": f"De Novo Mini-Binder Design against {cfg.get('target_name','the target')}"})
    blocks.append({"type": "subtitle",
                   "text": "RFdiffusion \u2192 ProteinMPNN \u2192 Boltz-2 co-folding validation"})
    blocks.append({"type": "attribution",
                   "text": f"{cfg.get('author_line','Generated by Biomni')} | {datestr}"})

    # ---------- Executive summary ----------
    top = rank.sort_values("iptm", ascending=False).reset_index(drop=True)
    winner = top.iloc[0]
    wtier = str(winner.get("confidence_tier", "")).split(" ")[0] if "confidence_tier" in top.columns else ""
    corr_note = cfg.get("correlation_note") or compute_correlation_note(rank) or ""
    # winner hotspot recovery
    winner_md = metrics.get(winner["candidate"], {})
    winner_recovery = winner_md.get("hotspot_recovery", "")
    winner_status = winner_md.get("epitope_status", "")
    recovery_clause = ""
    if winner_recovery and winner_recovery != "0/0":
        recovery_clause = f" Hotspot recovery: {winner_recovery} ({winner_status})."
    elif winner_status == "NOT_ASSESSED":
        recovery_clause = " Hotspot recovery was not assessed (no hotspot set supplied)."
    # Structure parenthetical: PDB id (an input) plus FETCHED facts (method/resolution/
    # deposition). Never a hand-typed resolution; missing facts are simply omitted here.
    struct_paren = ""
    if cfg.get("target_pdb"):
        pdb_bits = [f"PDB {cfg['target_pdb']}"]
        _method = structure_fact(struct_meta, "experimental_method")
        _res = structure_fact(struct_meta, "resolution_A")
        if _method and isinstance(_res, (int, float)):
            pdb_bits.append(f"{_method} {_res:.2f} \u00c5")
        elif isinstance(_res, (int, float)):
            pdb_bits.append(f"{_res:.2f} \u00c5")
        elif _method:
            pdb_bits.append(str(_method))
        _dep = structure_fact(struct_meta, "deposition_date")
        if _dep:
            pdb_bits.append(f"deposited {_dep}")
        struct_paren = " (" + ", ".join(pdb_bits) + ")"
    exec_txt = (
        f"We designed de novo mini-binders ({cfg.get('binder_len_range','60-90')} aa) targeting "
        f"{cfg.get('target_name','the target')}"
        + struct_paren
        + f". {dcount('n_backbones')} backbones were generated with RFdiffusion, redesigned with "
        f"ProteinMPNN into {dcount('n_sequences')} sequences, filtered to "
        f"{dcount('n_passed')} quality-passing candidates, and {dcount('n_validated')} "
        f"were validated by Boltz-2 co-folding. The top candidate, <b>{winner['candidate']}</b>, "
        f"folds against the target with ipTM = {winner['iptm']:.4f}"
        + (f" and interface PAE = {winner['iface_pae']:.2f} \u00c5" if "iface_pae" in top.columns else "")
        + (f" ({wtier} confidence)." if wtier else ".")
        + recovery_clause
        + (f" {corr_note}" if corr_note else "")
    )
    section("Executive Summary")
    para(exec_txt)

    # ---------- 1. Target & rationale ----------
    section("1. Target and Rationale")
    realised_range, span_explanation = construct_span_bits(cfg, scope)
    meta_bits = []
    # Identifiers (these are inputs the user provided, not derived facts).
    for label, key in [("Protein", "target_name"), ("PDB", "target_pdb"),
                       ("UniProt", "target_uniprot")]:
        if cfg.get(key):
            meta_bits.append(f"<b>{label}:</b> {cfg[key]}")
    # Fetched structure facts -- shown as their fetched value or 'unavailable', never a
    # hand-typed number.
    if cfg.get("target_pdb"):
        meta_bits.append(f"<b>Resolution:</b> {resolution_str(struct_meta)}")
        meta_bits.append(f"<b>Method:</b> {structure_fact(struct_meta, 'experimental_method') or 'unavailable'}")
        meta_bits.append(f"<b>Deposited:</b> {structure_fact(struct_meta, 'deposition_date') or 'unavailable'}")
    # Construct span DERIVED from construct_scope.json (single source of truth).
    if realised_range:
        dom_label = (cfg.get("domain_label") or "").strip()
        dom_val = realised_range + (f" ({dom_label})" if dom_label else "")
        meta_bits.append(f"<b>Construct span:</b> {dom_val}")
    if meta_bits:
        para(" &nbsp;&bull;&nbsp; ".join(meta_bits))
    # State nominal-vs-realised explicitly so a reader never has to reconcile two numbers.
    if span_explanation:
        para(span_explanation)
    # Structure-metadata provenance line (where the fetched facts came from).
    if cfg.get("target_pdb"):
        prov = (struct_meta or {}).get("provenance") or {}
        if struct_meta and struct_meta.get("available"):
            para(f"<i>Structure metadata (resolution, method, deposition date) fetched from the RCSB "
                 f"PDB entry {prov.get('pdb_id', cfg['target_pdb'])} on {prov.get('fetched_at', '?')} "
                 f"via {prov.get('source_url', 'the RCSB Data REST API')}.</i>")
        else:
            err = prov.get("error", "no metadata sidecar")
            para(f"<i>Structure metadata could not be fetched from RCSB for PDB {cfg['target_pdb']} "
                 f"({err}); values are shown as unavailable rather than guessed.</i>")
    if cfg.get("rationale"):
        para(cfg["rationale"])
    if cfg.get("epitope_note"):
        para(cfg["epitope_note"])

    # ---------- 2. Methods ----------
    section("2. Methods")
    filt = cfg.get("filters", {})
    filt_txt = "; ".join(f"{k} {v}" for k, v in filt.items()) if filt else "standard quality filters"
    n_sel = dcount("n_selected", "N")
    methods_txt = (
        f"<b>Backbone generation.</b> RFdiffusion generated {dcount('n_backbones')} binder backbones "
        f"({cfg.get('binder_len_range','60-90')} aa) docked to the target epitope. "
        f"<b>Sequence design.</b> ProteinMPNN (soluble model) produced {dcount('n_sequences')} sequences "
        f"with the target held fixed. Sequences were filtered on {filt_txt}, leaving "
        f"{dcount('n_passed')}. The best sequence from each of the top {n_sel} backbones "
        f"(of {dcount('n_backbones')}) by ProteinMPNN score was carried into co-folding; "
        f"{dcount('n_validated')} completed Boltz-2 validation. "
        f"<b>Validation.</b> Selected candidates were co-folded with the target "
        f"using Boltz-2 (MSA server; single-sequence binder) and ranked by ipTM, interface PAE, and "
        f"interface contacts."
    )
    para(methods_txt)
    if figs.get("mpnn_scores"):
        figure(figs["mpnn_scores"],
               "Figure 1. ProteinMPNN score distribution of all designs; "
               "vertical lines mark the selected candidates.")

    # ---------- 3. Results ----------
    section("3. Results")

    # 3.1 ranking table (target contact res + hotspots columns)
    subsection("3.1 Candidate ranking")
    headers = ["Rank", "Cand", "Len", "MPNN", "ipTM", "iface PAE", "contacts",
               "target contact res", "hotspots", "confidence"]
    rows = []
    for _, r in top.iterrows():
        cid = r["candidate"]
        md = metrics.get(cid, {})
        hs_rec = md.get("hotspot_recovery", "")
        rows.append([
            int(r.get("rank", 0)) if "rank" in top.columns else "",
            r["candidate"],
            int(r["binder_len"]) if "binder_len" in top.columns and pd.notna(r["binder_len"]) else "",
            f"{r['mpnn_score']:.3f}" if "mpnn_score" in top.columns and pd.notna(r["mpnn_score"]) else "",
            f"{r['iptm']:.4f}",
            f"{r['iface_pae']:.2f}" if "iface_pae" in top.columns and pd.notna(r["iface_pae"]) else "",
            int(r["n_interface_atom_contacts"]) if "n_interface_atom_contacts" in top.columns else "",
            int(r["n_target_iface_res"]) if "n_target_iface_res" in top.columns else "",
            hs_rec,
            str(r.get("confidence_tier", "")).split(" (")[0],
        ])
    blocks.append({"type": "table", "headers": headers,
                   "rows": [[str(c) for c in row] for row in rows]})

    # OFF_TARGET danger callout after the ranking table
    off_target_cands = [cid for cid, md in metrics.items() if md.get("epitope_status") == "OFF_TARGET"]
    if off_target_cands:
        # gather hotspot info from any record that has it
        any_md = metrics.get(off_target_cands[0], {})
        hs_declared = any_md.get("hotspots_declared", [])
        hs_str = ", ".join(str(x) for x in hs_declared) if hs_declared else "the declared set"
        n_declared = len(hs_declared) if hs_declared else "N"
        cids_str = ", ".join(sorted(off_target_cands))
        callout("Off-target candidates",
                f"{cids_str} contact none of the {n_declared} declared hotspot residues ({hs_str}) "
                f"and bind a different face of the target. They are ranked here by interface confidence "
                f"only and are not on-target candidates.",
                role="danger")

    # NOT_ASSESSED warning callout
    not_assessed_cands = [cid for cid, md in metrics.items() if md.get("epitope_status") == "NOT_ASSESSED"]
    if not_assessed_cands:
        callout("Hotspot recovery not assessed",
                f"Hotspot recovery was not assessed for any candidate because no hotspot set was supplied "
                f"to analyze_interface.py. All candidates are ranked by interface confidence only; "
                f"on-target epitope recovery is not verified. Re-run analyze_interface.py with --hotspots "
                f"to score epitope recovery.",
                role="warning")

    if figs.get("boltz_metrics"):
        figure(figs["boltz_metrics"],
               "Figure 2. Boltz-2 validation metrics across candidates. Panel D shows "
               "the raw ProteinMPNN-vs-ipTM correlation (negative sign = metrics agree, "
               "since lower MPNN and higher ipTM are both better).")

    # 3.2 correlation callout
    if corr_note:
        callout("Design score vs binding confidence", corr_note, role="neutral")

    # 3.3 top candidate detail + sequences (terminology + hotspot recovery)
    subsection(f"3.2 Top {min(args.top_n, len(top))} candidates \u2014 interfaces and sequences")
    for _, r in top.head(args.top_n).iterrows():
        cid = r["candidate"]
        md = metrics.get(cid, {})
        epi = md.get("target_contact_residues", [])
        epi_str = ", ".join(str(x) for x in epi) if epi else "n/a"
        tier = str(r.get("confidence_tier", ""))
        hs_rec = md.get("hotspot_recovery", "")
        hs_recovered = md.get("hotspots_recovered", [])
        hs_recovered_str = ", ".join(str(x) for x in hs_recovered) if hs_recovered else "none"
        body = (f"ipTM {r['iptm']:.4f}"
                + (f", interface PAE {r['iface_pae']:.2f} \u00c5" if "iface_pae" in top.columns and pd.notna(r["iface_pae"]) else "")
                + (f", {int(r['n_interface_atom_contacts'])} heavy-atom contacts" if "n_interface_atom_contacts" in top.columns else "")
                + (f", {int(r['n_target_iface_res'])} target contact residues" if "n_target_iface_res" in top.columns else "")
                + f".<br/><b>Target contact residues (native numbering):</b> {epi_str}")
        if hs_rec and hs_rec != "0/0":
            body += f"<br/><b>Hotspot recovery:</b> {hs_rec} ({hs_recovered_str})"
        elif md.get("epitope_status") == "NOT_ASSESSED":
            body += f"<br/><b>Hotspot recovery:</b> not assessed (no hotspot set supplied)"
        callout(f"{cid} \u2014 {tier}", body, role="neutral")
        sequence(cid, md.get("seq", ""))

    if figs.get("interfaces"):
        figure(figs["interfaces"],
               "Figure 3. Target contact occupancy (top) and per-candidate contact "
               "footprints (bottom) on native target numbering.")

    # ---------- 4. Discussion & limitations ----------
    section("4. Discussion and Limitations")
    disc = (
        "These are computational designs. ipTM and interface PAE report the confidence of the "
        "predicted complex geometry, not measured binding affinity: high-confidence candidates are "
        "prioritized hypotheses, not validated binders. ProteinMPNN score reflects sequence "
        "recoverability of a backbone and does not by itself predict binding, which is why "
        "structure-based co-folding is used as an orthogonal filter. On-target epitope recovery "
        "(hotspot recovery) is a separate axis from ipTM/PAE: a high-ipTM design that recovers "
        "zero declared hotspots is an off-target fold, not a hit. Recommended next steps are "
        "experimental: recombinant expression, biophysical binding assays (SPR/BLI), and, where "
        "relevant, a functional/competition assay against the intended epitope. Sequences enriched "
        "in charged residues (a known ProteinMPNN tendency) may benefit from solubility and "
        "developability review before synthesis."
    )
    para(disc)

    # ---------- Appendix: all candidates (hotspot_recovery string) ----------
    section("Appendix A. All validated candidates")
    for cid, md in metrics.items():
        seq = md.get("seq", "")
        hs_rec = md.get("hotspot_recovery", "")
        hs_clause = f", hotspot recovery {hs_rec}" if hs_rec and hs_rec != "0/0" else ""
        para(f"<b>{cid}</b> (len {md.get('binder_len','?')}, ipTM "
             f"{md.get('iptm','?')}, iface PAE {md.get('iface_pae','?')} \u00c5{hs_clause})")
        sequence(cid, seq)

    # ---------- consistency gate ----------
    warnings = verify_report_inputs(cfg, rank, metrics, derived, struct_meta, scope,
                                    strict=not args.no_strict)

    # if --no-strict and there are warnings, add a provenance-warnings callout to the content
    if args.no_strict and warnings:
        warn_text = "<br/>".join(f"{i+1}. {w}" for i, w in enumerate(warnings))
        callout("Provenance warnings", warn_text, role="warning")

    # ---------- write STYLE-FREE report content ----------
    # This JSON is the single source the PDF is rendered from; it is not a second,
    # separately-authored report surface. The pdf-report-generation skill styles it.
    content = {
        "report_kind": "binder_design_campaign",
        "title": f"De Novo Binder Design \u2014 {cfg.get('target_name','')}",
        "subtitle": "RFdiffusion \u2192 ProteinMPNN \u2192 Boltz-2 co-folding validation",
        "generated": datestr,
        "target": {"name": cfg.get("target_name"), "pdb": cfg.get("target_pdb"),
                   "uniprot": cfg.get("target_uniprot")},
        "figures": figs,
        "blocks": blocks,
        "provenance_warnings": warnings,
    }
    os.makedirs(os.path.dirname(os.path.abspath(args.out)) or ".", exist_ok=True)
    with open(args.out, "w") as fh:
        json.dump(content, fh, indent=2, ensure_ascii=False)

    size = os.path.getsize(args.out)
    print(f"[build_report] consistency gate passed; wrote validated report content to {args.out} "
          f"({len(blocks)} content blocks, {size} bytes).")
    print("[build_report] Next (required): render this content into the final PDF via the "
          "pdf-report-generation skill, which owns the report styling "
          "(running-header and footer rules).")
    if warnings:
        print(f"[build_report] {len(warnings)} provenance warning(s) carried into the content (non-strict mode).")


if __name__ == "__main__":
    main()
