#!/usr/bin/env python3
"""Apply deterministic typography to a generated infographic.

GenerateImage owns the scientific middle panel. This compositor owns the two
text-dense bands where image models most often garble names, invent numeric
citations, or substitute fonts. The final image is therefore still generated by
Biomni, while its report title and evidence strip are rendered from the verified
spec using stock DejaVu fonts (shipped with Matplotlib), so the reproduced text
is deterministic and does not depend on any bundled brand font.
"""
from __future__ import annotations

import pathlib
import textwrap

from PIL import Image, ImageDraw, ImageFont


BACKGROUND = "#FAF9F3"
BLACK = "#000000"
MAGENTA = "#CC2FB2"
MUTED = "#514D47"
HEADER_FRACTION = 0.14
EVIDENCE_FRACTION = 0.20
PADDING_FRACTION = 0.025


def _font_dir() -> pathlib.Path:
    """Directory holding stock DejaVu TrueType faces (Matplotlib, then system)."""
    candidates: list[pathlib.Path] = []
    try:
        import matplotlib

        candidates.append(
            pathlib.Path(matplotlib.__file__).resolve().parent
            / "mpl-data" / "fonts" / "ttf"
        )
    except Exception:  # noqa: BLE001 - fall through to system locations
        pass
    candidates += [
        pathlib.Path("/usr/share/fonts/truetype/dejavu"),
        pathlib.Path("/usr/share/fonts/dejavu"),
    ]
    for directory in candidates:
        try:
            if (directory / "DejaVuSans.ttf").exists():
                return directory
        except OSError:
            continue
    return candidates[0] if candidates else pathlib.Path(".")


FONT_DIR = _font_dir()


def _brand_safe_text(value: object) -> str:
    """Spell out comparison operators for robustness across renderers."""
    return str(value or "").strip().replace("≥", "at least ").replace(
        "≤", "at most ")


def _font(name: str, size: int) -> ImageFont.FreeTypeFont:
    return ImageFont.truetype(str(FONT_DIR / name), size=max(10, size))


def _fit(draw: ImageDraw.ImageDraw, text: str, font_name: str,
         initial_size: int, max_width: int, minimum_size: int) -> ImageFont.FreeTypeFont:
    size = initial_size
    while size > minimum_size:
        font = _font(font_name, size)
        if draw.textbbox((0, 0), text, font=font)[2] <= max_width:
            return font
        size -= 1
    return _font(font_name, minimum_size)


def _wrap_pixels(draw: ImageDraw.ImageDraw, text: str, font: ImageFont.FreeTypeFont,
                 max_width: int, max_lines: int) -> list[str]:
    lines: list[str] = []
    current = ""
    for word in text.split():
        candidate = f"{current} {word}".strip()
        if draw.textbbox((0, 0), candidate, font=font)[2] <= max_width:
            current = candidate
            continue
        if current:
            lines.append(current)
        current = word
        if len(lines) == max_lines - 1:
            break
    if current and len(lines) < max_lines:
        lines.append(current)
    if len(" ".join(lines)) < len(text):
        last = lines[-1]
        while last and draw.textbbox((0, 0), last + "…", font=font)[2] > max_width:
            last = last[:-1].rstrip()
        lines[-1] = last + "…"
    return lines


def compose(source: pathlib.Path, destination: pathlib.Path, spec: dict) -> None:
    """Cover reserved bands and render verified header/evidence text into them."""
    with Image.open(source) as opened:
        image = opened.convert("RGB")
    width, height = image.size
    draw = ImageDraw.Draw(image)
    header_height = round(height * HEADER_FRACTION)
    evidence_height = round(height * EVIDENCE_FRACTION)
    evidence_top = height - evidence_height
    padding = round(width * PADDING_FRACTION)

    draw.rectangle((0, 0, width, header_height), fill=BACKGROUND)
    draw.rectangle((0, evidence_top, width, height), fill=BACKGROUND)
    draw.line((padding, header_height - 1, width - padding, header_height - 1),
              fill="#D8D4CC", width=max(1, height // 700))
    draw.line((padding, evidence_top, width - padding, evidence_top),
              fill="#D8D4CC", width=max(1, height // 700))

    subject = " — ".join(filter(None, (
        _brand_safe_text(spec.get("SUBJECT")),
        _brand_safe_text(spec.get("SUBJECT_LONG")),
    )))
    context = " · ".join(filter(None, (
        _brand_safe_text(spec.get("SUBJECT_CLASS_SHORT")),
        _brand_safe_text(spec.get("CONTEXT")),
        _brand_safe_text(spec.get("HEADLINE_TAG")),
    )))
    subject_font = _fit(
        draw, subject, "DejaVuSerif.ttf", round(height * 0.042),
        width - 2 * padding, round(height * 0.024),
    )
    context_font = _fit(
        draw, context, "DejaVuSans.ttf", round(height * 0.023),
        width - 2 * padding, round(height * 0.018),
    )
    subject_box = draw.textbbox((0, 0), subject, font=subject_font)
    subject_height = subject_box[3] - subject_box[1]
    context_lines = _wrap_pixels(
        draw, context, context_font, width - 2 * padding, max_lines=2)
    draw.text((padding, round(header_height * 0.16)),
              subject, font=subject_font, fill=BLACK)
    draw.multiline_text(
        (padding, round(header_height * 0.22) + subject_height),
        "\n".join(context_lines), font=context_font, fill=MUTED,
        spacing=max(1, context_font.size // 6),
    )

    column_gap = round(width * 0.025)
    column_width = (width - 2 * padding - 2 * column_gap) // 3
    evidence_font = _font("DejaVuSans.ttf", round(height * 0.022))
    bullet_radius = max(4, round(height * 0.006))
    for index in range(3):
        text = _brand_safe_text(spec.get(f"EVIDENCE_{index + 1}"))
        x = padding + index * (column_width + column_gap)
        y = evidence_top + round(evidence_height * 0.22)
        draw.ellipse((x, y + bullet_radius, x + 2 * bullet_radius,
                      y + 3 * bullet_radius), fill=MAGENTA)
        line_width = max(24, int(column_width / max(8, evidence_font.size * 0.56)))
        wrapped = textwrap.wrap(text, width=line_width, break_long_words=False)
        draw.multiline_text(
            (x + 3 * bullet_radius, y), "\n".join(wrapped[:4]),
            font=evidence_font, fill=BLACK, spacing=max(2, evidence_font.size // 5),
        )

    destination.parent.mkdir(parents=True, exist_ok=True)
    image.save(destination, format="PNG", optimize=True)
