#!/usr/bin/env python3
"""
build_druggability_report.py — assemble the Phylo-branded target-druggability PDF, for ANY target.

Consumes the JSON artifacts + figures produced by the other scripts and an optional infographic
PNG (made separately with GenerateImage) and produces a report with:
  title page, executive summary, methods, results (tractability / structure / drugs / scorecard),
  conclusion (most viable modality), caveats/limitations, next steps, and references.

References are passed in as a JSON list of {n, text} so the caller controls citation numbering to
match the inline [N] markers it wrote from LiteratureSearch. This script NEVER invents citations.

Usage:
    python build_druggability_report.py --config report_config.json

report_config.json schema (all paths absolute):
{
  "target_symbol": "KRAS",
  "ot_json": ".../KRAS_opentargets.json",
  "pockets_json": ".../KRAS_pockets.json",       # optional
  "scores_json": ".../KRAS_modality_scores.json",
  "figures": {"tractability": ".../fig1.png", "pockets": ".../fig2.png",
              "scorecard": ".../fig3.png", "infographic": ".../infographic.png"},
  "narrative": {                                   # prose the agent wrote (grounded, with [N])
     "executive_summary": "...", "intro": "...", "structure_context": "...",
     "modality_discussion": "...", "next_steps": ["...", "..."]
  },
  "references": [{"n": 1, "text": "Author et al. Journal Year. Title."}, ...],
  "disease": "lung carcinoma",                     # optional
  "out": ".../report_KRAS_druggability.pdf"
}

Requires: reportlab, pypdf.
"""
import argparse
import datetime as dt
import json
import os

from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import (HRFlowable, Image, KeepTogether, PageBreak, Paragraph,
                                SimpleDocTemplate, Spacer, Table, TableStyle)

# ---- Phylo brand ----
PHYLO_GOLD = HexColor("#D4A04A"); PHYLO_BLUE = HexColor("#0279EE")
PHYLO_GREEN = HexColor("#75A025"); PHYLO_ORANGE = HexColor("#FF9400")
HEADING = HexColor("#111111"); BODY = HexColor("#2C2A26"); MUTED = HexColor("#8A8378")
TABLE_HEADER_BG = PHYLO_GOLD; TABLE_HEADER_FG = HexColor("#FFFFFF")
TABLE_ALT = HexColor("#F9F7F3"); TABLE_BORDER = HexColor("#D5CFC5")
CALLOUT_BG = HexColor("#FAF9F3")
CONTENT_W = letter[0] - 120  # 60pt margins

MOD_NAMES = {"SM": "Small molecule", "AB": "Antibody", "PR": "PROTAC / degrader",
             "OC": "Other clinical"}
VERDICT_COLOR = {"High / most viable": PHYLO_GREEN, "Medium / emerging": PHYLO_ORANGE,
                 "Low": MUTED, "Not viable": HexColor("#B00020")}


def styles_for(title):
    ss = getSampleStyleSheet()
    def add(name, **kw):
        if name in ss.byName:
            for k, v in kw.items():
                setattr(ss[name], k, v)
        else:
            ss.add(ParagraphStyle(name=name, **kw))
    add("ReportTitle", fontName="Helvetica-Bold", fontSize=25, textColor=HEADING,
        spaceAfter=6, leading=30)
    add("Subtitle", fontName="Helvetica", fontSize=12, textColor=PHYLO_GOLD, spaceAfter=4)
    add("Attribution", fontName="Helvetica-Oblique", fontSize=10, textColor=MUTED, spaceAfter=8)
    add("SectionHead", fontName="Helvetica-Bold", fontSize=16, textColor=HEADING,
        spaceBefore=18, spaceAfter=8)
    add("SubHead", fontName="Helvetica-Bold", fontSize=12, textColor=HEADING,
        spaceBefore=10, spaceAfter=4)
    add("Body", fontName="Helvetica", fontSize=10.3, textColor=BODY, alignment=TA_JUSTIFY,
        spaceAfter=7, leading=14.5)
    add("Caption", fontName="Helvetica-Oblique", fontSize=8.6, textColor=MUTED,
        alignment=TA_CENTER, spaceAfter=12)
    add("CellL", fontName="Helvetica", fontSize=8.6, textColor=BODY, alignment=TA_LEFT, leading=11)
    add("CellHdr", fontName="Helvetica-Bold", fontSize=8.8, textColor=TABLE_HEADER_FG,
        alignment=TA_LEFT, leading=11)
    add("RefText", fontName="Helvetica", fontSize=8.8, textColor=BODY, alignment=TA_LEFT,
        leading=12, spaceAfter=3)
    return ss


def header_footer(title):
    def cb(canvas, doc):
        canvas.saveState()
        w, h = letter
        canvas.setFont("Helvetica", 9); canvas.setFillColor(MUTED)
        canvas.drawString(60, h - 40, title[:90])
        canvas.setStrokeColor(PHYLO_GOLD); canvas.setLineWidth(1)
        canvas.line(60, h - 48, w - 60, h - 48)
        canvas.setStrokeColor(TABLE_BORDER); canvas.setLineWidth(0.75)
        canvas.line(60, 40, w - 60, 40)
        canvas.setFont("Helvetica", 8); canvas.setFillColor(MUTED)
        canvas.drawCentredString(w / 2, 26, f"Page {doc.page}")
        canvas.drawRightString(w - 60, 26, "Generated by Biomni")
        canvas.restoreState()
    return cb


def para(text, ss, style="Body"):
    return Paragraph(text, ss[style])


def truncate_words(text, maxlen):
    """Truncate at a word boundary with an ellipsis; never cut mid-word."""
    text = (text or "").strip()
    if len(text) <= maxlen:
        return text
    cut = text[:maxlen].rsplit(" ", 1)[0]
    return cut + "\u2026"


def _safe_str(value, default=""):
    """Coerce a nullable / NaN / non-string value to a ReportLab-safe string.

    Handles None, float('nan')/float('inf'), numbers, and XML-escapes the result so
    Paragraph() never receives raw ``<``/``>``/``&`` from data values (a common crash
    when a mechanism-of-action or label contains angle brackets). ``default`` is used
    for None/NaN/empty so the report shows a clean dash instead of the literal text
    "None" or "nan".
    """
    if value is None:
        return default
    if isinstance(value, float):
        import math
        if math.isnan(value) or math.isinf(value):
            return default
    if isinstance(value, (int, float)):
        s = str(value)
    else:
        s = str(value).strip()
    if s == "" or s.lower() in ("none", "nan", "null"):
        return default
    # escape XML metacharacters so Paragraph() (which parses inline markup) won't crash
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _as_bullets(value, default):
    """Normalize a caveats/next_steps field into a list of bullet strings.

    Accepts a list of strings, a single string (treated as one bullet), or
    None/empty (falls back to `default`). Prevents the classic bug where a
    plain string gets iterated character-by-character.
    """
    if value is None or value == "" or value == []:
        return default
    if isinstance(value, str):
        return [value.strip()]
    if isinstance(value, (list, tuple)):
        return [str(v).strip() for v in value if str(v).strip()]
    return default


def divider():
    return HRFlowable(width=CONTENT_W, thickness=1, color=PHYLO_GOLD, spaceAfter=8, spaceBefore=2)


def callout(text, ss, accent=PHYLO_GOLD):
    t = Table([[para(text, ss)]], colWidths=[CONTENT_W])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), CALLOUT_BG),
        ("BOX", (0, 0), (-1, -1), 0.5, TABLE_BORDER),
        ("LINEBEFORE", (0, 0), (0, -1), 3, accent),
        ("TOPPADDING", (0, 0), (-1, -1), 10), ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 14), ("RIGHTPADDING", (0, 0), (-1, -1), 12),
    ]))
    t.hAlign = "CENTER"
    return t


def styled_table(header, rows, ss, colw):
    data = [[Paragraph(f"<b>{h}</b>", ss["CellHdr"]) for h in header]]
    for r in rows:
        data.append([Paragraph(_safe_str(c), ss["CellL"]) for c in r])
    t = Table(data, colWidths=colw, repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), TABLE_HEADER_BG),
        ("TEXTCOLOR", (0, 0), (-1, 0), TABLE_HEADER_FG),
        ("GRID", (0, 0), (-1, -1), 0.5, TABLE_BORDER),
        ("BOX", (0, 0), (-1, -1), 0.75, TABLE_BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 5), ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 7), ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]
    for i in range(2, len(data), 2):
        style.append(("BACKGROUND", (0, i), (-1, i), TABLE_ALT))
    t.setStyle(TableStyle(style))
    t.hAlign = "CENTER"
    return t


def fig_block(path, caption, ss, max_w=CONTENT_W, max_h=300):
    if not path or not os.path.exists(path):
        return None
    from reportlab.lib.utils import ImageReader
    iw, ih = ImageReader(path).getSize()
    scale = min(max_w / iw, max_h / ih)
    img = Image(path, width=iw * scale, height=ih * scale)
    img.hAlign = "CENTER"
    return KeepTogether([img, Spacer(1, 3), para(caption, ss, "Caption")])


def build(cfg):
    ss = styles_for(f"{cfg['target_symbol']} Druggability Assessment")
    ot = json.load(open(cfg["ot_json"]))
    scores = json.load(open(cfg["scores_json"]))
    pockets = json.load(open(cfg["pockets_json"])) if cfg.get("pockets_json") and \
        os.path.exists(cfg["pockets_json"]) else {}
    nar = cfg.get("narrative", {})
    figs = cfg.get("figures", {})
    sym = cfg["target_symbol"]
    tgt = ot["target"]
    dv = ot.get("data_version", {})
    dv_str = f"{dv.get('year','?')}.{dv.get('month','?')}" if dv else "n/a"
    date_str = dt.date.today().strftime("%B %d, %Y")

    story = []
    # ---- Title
    story += [Spacer(1, 30),
              para(f"{sym} Druggability &amp; Tractability Assessment", ss, "ReportTitle")]
    sub = f"Target-centric druggability across modalities"
    if cfg.get("disease"):
        sub += f" · disease context: {cfg['disease']}"
    story += [para(sub, ss, "Subtitle"),
              para(f"<i>Generated by Biomni | {date_str} | Open Targets data {dv_str}</i>",
                   ss, "Attribution"),
              divider()]

    # ---- Infographic (conceptual summary, GenerateImage)
    ib = fig_block(figs.get("infographic"),
                   f"Figure 1. Visual summary of the {sym} druggability assessment.",
                   ss, max_h=340)
    if ib:
        story += [ib]

    # ---- Executive summary
    story += [para("Executive Summary", ss, "SectionHead")]
    if nar.get("executive_summary"):
        for p in nar["executive_summary"].split("\n\n"):
            story.append(para(p, ss))
    # verdict callout
    top = scores["ranked"][0] if scores.get("ranked") else None
    if top:
        top_mod = top.get("modality", "")
        top_verdict = top.get("verdict", "")
        vc = VERDICT_COLOR.get(top_verdict, PHYLO_GOLD)
        frontier = scores.get("frontier")
        ftxt = ""
        if frontier and frontier != top_mod:
            ftxt = (f" The highest-potential emerging modality is "
                    f"<b>{MOD_NAMES.get(frontier, frontier)}</b>.")
        story.append(callout(
            f"<b>Most viable modality: {MOD_NAMES.get(top_mod, top_mod)} "
            f"({top_verdict}).</b>{ftxt}", ss, accent=vc))

    # ---- Methods
    story += [para("Methods", ss, "SectionHead"),
              para("This assessment integrates three independent evidence streams for a human "
                   "protein-coding target:", ss),
              para("<b>1. Tractability &amp; annotations.</b> Target identifiers were resolved via "
                   "the Open Targets Platform GraphQL API, which also provided tractability buckets "
                   "across all modalities, curated known drugs / clinical candidates, DepMap gene "
                   "essentiality (negative gene-effect = dependency), and curated safety "
                   f"liabilities (data release {dv_str}).", ss),
              para("<b>2. Structural pocket detection.</b> A representative 3D structure was "
                   "retrieved (best experimental PDB by ligand-bound state and resolution, with an "
                   "AlphaFold predicted model as fallback), cleaned to a single chain with waters "
                   "removed, and analysed with fpocket. The top pocket by druggability score is "
                   "reported (>0.5 druggable, 0.2-0.5 borderline, &lt;0.2 poorly druggable) and "
                   "annotated relative to any bound ligand.", ss),
              para("<b>3. Literature context.</b> Peer-reviewed evidence was retrieved with the "
                   "Biomni LiteratureSearch tool; all statements are grounded in retrieved records "
                   "and cited inline.", ss),
              para("<b>Scorecard.</b> Each modality is scored 0-3 (None/Low/Med/High) on "
                   "tractability, structural support, and clinical precedent; the overall score is "
                   "their rounded mean, with ties broken toward clinical precedent.", ss)]

    # ---- Results: target snapshot
    story += [PageBreak(), para("Results", ss, "SectionHead"),
              para("Target snapshot", ss, "SubHead")]
    dm = ot.get("depmap_essentiality", {})
    snap_rows = [
        ["Approved symbol", _safe_str(tgt.get("symbol"))],
        ["Approved name", _safe_str(tgt.get("approvedName"))],
        ["Ensembl ID", _safe_str(tgt.get("ensembl"))],
        ["UniProt", _safe_str(tgt.get("uniprot"), "n/a")],
        ["Biotype", _safe_str(tgt.get("biotype"))],
        ["Flagged essential (OT)", _safe_str(ot.get("isEssential"))],
        ["DepMap screens", _safe_str(dm.get("n_screens"), "n/a")],
        ["DepMap mean gene-effect", _safe_str(dm.get("mean_gene_effect"), "n/a")],
        ["Fraction dependent (&lt;-0.5)", _safe_str(dm.get("frac_dependent_lt_-0.5"), "n/a")],
        ["Curated safety liabilities", _safe_str(len(ot.get("safety_liabilities", [])))],
    ]
    if ot.get("disease_association"):
        da = ot["disease_association"]
        snap_rows.append([f"Assoc. score ({_safe_str(da.get('diseaseName'), 'disease')})",
                          _safe_str(da.get("association_score"))])
    story += [styled_table(["Attribute", "Value"], snap_rows, ss, [200, CONTENT_W - 200]),
              Spacer(1, 8)]

    # ---- Tractability
    story += [para("Modality tractability (Open Targets)", ss, "SubHead")]
    if nar.get("tractability_note"):
        story.append(para(nar["tractability_note"], ss))
    tb = fig_block(figs.get("tractability"),
                   f"Figure 2. Open Targets tractability buckets for {sym} by modality "
                   "(green = criterion met).", ss, max_h=290)
    if tb:
        story.append(tb)
    tract_rows = []
    for m, v in ot["tractability"].items():
        true_list = v.get("true", []) if isinstance(v, dict) else []
        tract_rows.append([MOD_NAMES.get(m, m),
                           f"{v.get('n_true', 0)}/{v.get('n_total', 0)}" if isinstance(v, dict) else "\u2014",
                           ", ".join(true_list) or "\u2014"])
    story += [styled_table(["Modality", "Met", "Buckets met"], tract_rows, ss,
                           [110, 44, CONTENT_W - 154]), Spacer(1, 8)]

    # ---- Structure / pockets
    story += [para("Structural pocket analysis (fpocket)", ss, "SubHead")]
    if nar.get("structure_context"):
        story.append(para(nar["structure_context"], ss))
    pb = fig_block(figs.get("pockets"),
                   "Figure 3. Top-pocket druggability score per analysed structure.", ss, max_h=280)
    if pb:
        story.append(pb)
    prows = []
    for k, p in pockets.items():
        if isinstance(p, dict) and p.get("drug_score") is not None:
            import math
            ds = p["drug_score"]
            score_str = f"{ds:.3f}" if isinstance(ds, (int, float)) and not (
                isinstance(ds, float) and (math.isnan(ds) or math.isinf(ds))) else "\u2014"
            vol = p.get("volume")
            vol_str = f"{vol:.0f}" if isinstance(vol, (int, float)) and not (
                isinstance(vol, float) and (math.isnan(vol) or math.isinf(vol))) else "\u2014"
            prows.append([_safe_str(p.get("label", k)),
                          score_str,
                          _safe_str(p.get("druggable_class")),
                          vol_str,
                          _safe_str(p.get("n_pocket_residues")),
                          _safe_str(p.get("location_label"))])
    if prows:
        story += [styled_table(["Structure", "Score", "Class", "Vol (A<super>3</super>)",
                                "Res.", "Location"], prows, ss,
                               [92, 40, 70, 50, 34, CONTENT_W - 286]), Spacer(1, 8)]
    else:
        story.append(callout("No usable 3D structure was available (no suitable experimental "
                             "PDB and no AlphaFold model), so structural pocket detection was "
                             "skipped for this target.", ss, accent=PHYLO_ORANGE))

    # ---- Known drugs
    drugs = ot.get("drugs", {})
    story += [para(f"Known drugs &amp; clinical candidates (n = {drugs.get('count', 0)})",
                   ss, "SubHead")]
    drows = []
    for r in drugs.get("rows", [])[:15]:
        stage = r.get("maxClinicalStage")
        drows.append([_safe_str(r.get("name")),
                      _safe_str(r.get("drugType")),
                      _safe_str(stage if stage is not None else ""),
                      truncate_words(_safe_str(r.get("mechanismOfAction")), 90)])
    if drows:
        story.append(styled_table(["Drug", "Type", "Max stage", "Mechanism"], drows, ss,
                                  [96, 84, 74, CONTENT_W - 254]))
        if drugs.get("count", 0) > 15:
            story.append(para(f"<i>Showing top 15 of {drugs['count']}; full list in the data "
                              f"JSON. Curated list \u2014 not an exhaustive competitive "
                              f"landscape.</i>", ss, "Caption"))
    else:
        story.append(para("No curated drugs or clinical candidates in Open Targets for this "
                          "target.", ss))

    # ---- Scorecard
    story += [PageBreak(), para("Modality viability scorecard", ss, "SectionHead")]
    sb = fig_block(figs.get("scorecard"),
                   "Figure 4. Modality viability scorecard across evidence dimensions.", ss,
                   max_h=300)
    if sb:
        story.append(sb)
    srows = []
    for r in scores.get("ranked", []):
        srows.append([MOD_NAMES.get(r.get("modality", ""), r.get("modality", "")),
                      _safe_str(r.get("tractability")),
                      _safe_str(r.get("structural")),
                      _safe_str(r.get("clinical")),
                      _safe_str(r.get("overall")),
                      _safe_str(r.get("verdict"))])
    story += [styled_table(["Modality", "Tract.", "Struct.", "Clin.", "Overall", "Verdict"],
                           srows, ss, [120, 46, 46, 44, 52, CONTENT_W - 308]), Spacer(1, 6),
              para("<i>Scores: 0 = None, 1 = Low, 2 = Medium, 3 = High. NA = not assessed "
                   "(no structure available; excluded from the overall mean). This is a "
                   "transparent triage heuristic, not a prediction of clinical success.</i>",
                   ss, "Caption")]

    # ---- Discussion / conclusion
    story += [para("Conclusion", ss, "SectionHead")]
    if nar.get("modality_discussion"):
        for p in nar["modality_discussion"].split("\n\n"):
            story.append(para(p, ss))

    # ---- Caveats
    story += [para("Caveats &amp; limitations", ss, "SectionHead")]
    default_caveats = [
        "Open Targets tractability buckets are heuristic flags, not proof that a drug program "
        "will succeed; an 'Approved Drug' bucket can coexist with a 'High-Quality Pocket' bucket "
        "being false (e.g. covalent or cryptic-pocket strategies).",
        "fpocket scores are geometry-based and conformation-dependent. A high score on a drug-bound "
        "crystal partly reflects that the pocket was captured in its open state; adjacent sub-"
        "pockets can merge and inflate volume.",
        "AlphaFold-model pockets (when used as fallback) are less reliable than experimental ones.",
        "The curated known-drugs list is a snapshot, not an exhaustive competitive landscape.",
        "A favourable pocket or tractability signal is a hypothesis for experimental follow-up, "
        "not a validated druggable site.",
    ]
    for c in _as_bullets(nar.get("caveats"), default_caveats):
        story.append(para(f"\u2022 {c}", ss))

    # ---- Next steps
    story += [para("Suggested next steps", ss, "SectionHead")]
    for s in _as_bullets(nar.get("next_steps"), []):
        story.append(para(f"\u2022 {s}", ss))

    # ---- References
    refs = cfg.get("references", [])
    if refs:
        story += [para("References", ss, "SectionHead")]
        for r in refs:
            story.append(para(f"{r['n']}. {r['text']}", ss, "RefText"))

    out = cfg["out"]
    os.makedirs(os.path.dirname(out), exist_ok=True)
    doc = SimpleDocTemplate(out, pagesize=letter, topMargin=58, bottomMargin=52,
                            leftMargin=60, rightMargin=60,
                            title=f"{sym} Druggability Assessment", author="Biomni")
    cb = header_footer(f"{sym} Druggability Assessment")
    doc.build(story, onFirstPage=cb, onLaterPages=cb)
    return out


def validate(path):
    from pypdf import PdfReader
    reader = PdfReader(path)
    n = len(reader.pages)
    size = os.path.getsize(path)
    assert n >= 4, f"only {n} pages"
    assert size > 5000, f"only {size} bytes"
    assert len(reader.pages[0].extract_text().strip()) > 0, "no text on page 1"
    return {"pages": n, "bytes": size}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True)
    args = ap.parse_args()
    cfg = json.load(open(args.config))
    out = build(cfg)
    info = validate(out)
    print(f"[report] wrote {out} ({info['pages']} pages, {info['bytes']} bytes)")


if __name__ == "__main__":
    main()
